# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reminder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reminder.proto',
  package='rusad_bot',
  syntax='proto2',
  serialized_pb=_b('\n\x0ereminder.proto\x12\trusad_bot\"1\n\x08reminder\x12\x0b\n\x03uid\x18\x01 \x02(\x03\x12\x0b\n\x03ttw\x18\x02 \x02(\x03\x12\x0b\n\x03mes\x18\x03 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REMINDER = _descriptor.Descriptor(
  name='reminder',
  full_name='rusad_bot.reminder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='rusad_bot.reminder.uid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ttw', full_name='rusad_bot.reminder.ttw', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mes', full_name='rusad_bot.reminder.mes', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['reminder'] = _REMINDER

reminder = _reflection.GeneratedProtocolMessageType('reminder', (_message.Message,), dict(
  DESCRIPTOR = _REMINDER,
  __module__ = 'reminder_pb2'
  # @@protoc_insertion_point(class_scope:rusad_bot.reminder)
  ))
_sym_db.RegisterMessage(reminder)


# @@protoc_insertion_point(module_scope)
